# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comercio',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='comercios',
            field=models.ManyToManyField(to='areas.Area'),
        ),
    ]
