# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('array', models.CharField(max_length=2500)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
